spring.config.activate.on-profile=local

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/${POSTGRES_DB:canteiro}}
spring.datasource.username=${DATABASE_USERNAME:${POSTGRES_USER:canteiro}}
spring.datasource.password=${DATABASE_PASSWORD:${POSTGRES_PASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
