spring.config.activate.on-profile=test

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.flyway.enabled=true
security.jwt.issuer=canteiro.io-test
security.jwt.secret=test-only-signing-secret-with-at-least-thirty-two-characters
security.jwt.access-token-ttl=PT15M
security.jwt.refresh-token-ttl=P30D
security.account-activation.token-ttl=PT24H
security.account-activation.email-from=test@canteiro.io
security.password-reset.token-ttl=PT1H
security.password-reset.email-from=test@canteiro.io
